id: P004330
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD179846
  title: མི་ཉག་ཐུབ་བསྟན་ཆོས་དར་གྱི་དཔྱད་རྩོམ་ཁག་གཉིས།
  author: ''
  volumes:
    7a8addac6d4b43e7b5041c58bd355faf:
      image_group_id: I1KG16282
      title: ''
      volume_number: 1
      total_pages: 53
