id: ID15F3534
legacy_id: P004330
ocr_import_info:
  bdrc_scan_id: W1PD179846
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T08:48:49'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T08:59:51.077191+00:00'
last_modified: 2022-08-27 16:59:57.963018
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1PD179846
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1PD179846
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མི་ཉག་ཐུབ་བསྟན་ཆོས་དར་གྱི་དཔྱད་རྩོམ་ཁག་གཉིས།
  author: མི་ཉག་པ་ཐུབ་བསྟན་ཆོས་དར།
statistics:
  ocr_word_mean_confidence_index: 0.96801325481459
  ocr_word_median_confidence_index: 0.9900000095367432
quality: null
bases:
  I1KG16282:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG16282
      total_pages: 53
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG16282.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.96801325481459
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
